version: 2.1

orbs:
  python: circleci/python@<<pipeline.parameters.orb-python-version>>

parameters:
  orb-python-version:
    type: string
    default: 1.4.0
    
workflows:
  version: 2
  WORKFLOW_NAME_!:
    jobs:
      - JOB_NAME_1

jobs:
  JOB_NAME_1:
    executor: python/default
    steps:
      - checkout
      - run:
          command: "uname -a"
      - run:
          command: "pwd && id && lsb_release -a && ip address"
      - python/install-packages:
          args: pytest
          pkg-manager: pip
          
